// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/audit": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "审计记录"
                ],
                "summary": "分页获取审计记录",
                "parameters": [
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mgp.Result-mgp_PaginateData-array_model_Audit"
                        }
                    }
                }
            }
        },
        "/api/audit/{pk}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "审计记录"
                ],
                "summary": "获取指定ID的审计记录",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "pk",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mgp.Result-model_Audit"
                        }
                    }
                }
            }
        },
        "/{pk}": {
            "get": {
                "parameters": [
                    {
                        "type": "integer",
                        "name": "pk",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "mgp.PaginateData-array_model_Audit": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/model.Audit"
                        }
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "mgp.Result-mgp_PaginateData-array_model_Audit": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "返回数据/错误详细信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/mgp.PaginateData-array_model_Audit"
                        }
                    ]
                },
                "msg": {
                    "description": "请求结果",
                    "type": "string"
                }
            }
        },
        "mgp.Result-model_Audit": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "返回数据/错误详细信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Audit"
                        }
                    ]
                },
                "msg": {
                    "description": "请求结果",
                    "type": "string"
                }
            }
        },
        "model.Audit": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "failed_reason": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "new_data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "operation": {
                    "type": "string"
                },
                "original_data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "$ref": "#/definitions/model.AuditStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.AuditStatus": {
            "type": "string",
            "enum": [
                "success",
                "failed",
                "running"
            ],
            "x-enum-varnames": [
                "AuditSuccess",
                "AuditFailed",
                "AuditRunning"
            ]
        },
        "url.Values": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"https", "http"},
	Title:            "My Gin Plus Example API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
